### ISSUE TITLE
Travis stop working

### ISSUE THREAD

**Issue by aloctavodia** [BIOS-IMASL/bomeba0#68]
Travis is configured, but PR does not activate the building process, in fact Travis is unaware of PRs.

**Comment by PabloGGaray** [comment]
Just to save the details. Was needed a migration of the account of Travis from [Legacy GitHub Services to GitHub Apps](https://docs.travis-ci.com/user/migrate/legacy-services-to-github-apps-migration-guide/), to run Travis in the PR.
